// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw8SKGCoGOKakjXCGrt1qJPMRlm0F8pxY',
    appId: '1:1061620812204:web:bcc85d4d3c0f20d49b9209',
    messagingSenderId: '1061620812204',
    projectId: 'flutterpractice-67142',
    authDomain: 'flutterpractice-67142.firebaseapp.com',
    storageBucket: 'flutterpractice-67142.firebasestorage.app',
    measurementId: 'G-F91V1D1QFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGaHWVOuJ6UDSZr_P1jbY9kzn8hfbfGAY',
    appId: '1:1061620812204:android:9a2c3a6d806d1c149b9209',
    messagingSenderId: '1061620812204',
    projectId: 'flutterpractice-67142',
    storageBucket: 'flutterpractice-67142.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDJ9Nrmv4WgufBuLEc2I8YCI2WbFA504o',
    appId: '1:1061620812204:ios:c0f23227526645ed9b9209',
    messagingSenderId: '1061620812204',
    projectId: 'flutterpractice-67142',
    storageBucket: 'flutterpractice-67142.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDJ9Nrmv4WgufBuLEc2I8YCI2WbFA504o',
    appId: '1:1061620812204:ios:c0f23227526645ed9b9209',
    messagingSenderId: '1061620812204',
    projectId: 'flutterpractice-67142',
    storageBucket: 'flutterpractice-67142.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw8SKGCoGOKakjXCGrt1qJPMRlm0F8pxY',
    appId: '1:1061620812204:web:ecf07af45583ed1c9b9209',
    messagingSenderId: '1061620812204',
    projectId: 'flutterpractice-67142',
    authDomain: 'flutterpractice-67142.firebaseapp.com',
    storageBucket: 'flutterpractice-67142.firebasestorage.app',
    measurementId: 'G-3CKH8YGL71',
  );
}
